<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVLmJiwG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVLmJiwG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVLmJiwG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVLmJiwG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVLmJiwG\App_KernelDevDebugContainer([
    'container.build_hash' => 'VLmJiwG',
    'container.build_id' => '35fb0f8d',
    'container.build_time' => 1605278809,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVLmJiwG');
